app/demo/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, HiddenField, StringField
from app.models import Subdomain, ModelType
from flask_wtf.file import FileField, FileAllowed


def get_subdomain_names():
    """retrieve list of choices for SelectField
    """
    return [(s.name, s.name) for s in Subdomain.query.all()]


def get_model_type_names():
    """retrieve list of choices for SelectField
    """
    return [(m.name, m.name) for m in ModelType.query.all()]


class SubdomainChoiceForm(FlaskForm):

    subdomain_id = SelectField("Type of application subdomain:")
    domain = HiddenField()
    bkg_file = FileField(
        "Select Background Dataset File (.csv):",
        validators=[FileAllowed(["csv"], "CSV file only!")],
    )
    explainer_file = FileField(
        "Select Explainer File (.csv):",
        validators=[FileAllowed(["csv"], "CSV file only!")],
    )
    model_type = SelectField("Select Model Type:")
    next = SubmitField("Next")


class SelectFeaturesForm(FlaskForm):
    next = SubmitField("Next")


class RangeGroupsForm(FlaskForm):
    feature = SelectField("Select Feature to Bin:")
    range_from = StringField("From:")
    range_to = StringField("To:")
    submit = SubmitField("Submit")
    next = SubmitField("Next")


class CategoriesForm(FlaskForm):
    category_name = StringField("Enter category name:")
    submit = SubmitField("Submit")
    next = SubmitField("Next")


class FinancialSelectFeatures(FlaskForm):
    next = SubmitField("Next")

app/demo/forms/__init__.py
from .initial import InitialForm  # noqa 401
from .subdomain_choice_form import SubdomainChoiceForm  # noqa 401
from .select_feature_form import SelectFeaturesForm  # noqa 401
from .range_groups_form import RangeGroupsForm  # noqa 401
from .categories_form import CategoriesForm  # noqa 401
from .financial_select_features import FinancialSelectFeatures  # noqa 401

app/demo/forms/categories_form.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField


class CategoriesForm(FlaskForm):
    category_name = StringField("Enter category name:")
    submit = SubmitField("Submit")
    next = SubmitField("Next")

app/demo/forms/financial_select_features.py
from flask_wtf import FlaskForm
from wtforms import SubmitField


class FinancialSelectFeatures(FlaskForm):
    next = SubmitField("Next")

app/demo/forms/select_feature_form.py
from flask_wtf import FlaskForm
from wtforms import SubmitField


class SelectFeaturesForm(FlaskForm):
    next = SubmitField("Next")

app/demo/controller.py
def prediction_score(prediction):
    return int(round(prediction, 2) * 100)


def predicted(prediction_score):
    if prediction_score < 50:
        return "No"
    else:
        return "Yes"


def age_range_groups(range_groups_ages, age):
    for age_range in range_groups_ages:
        min_age = int(age_range[0])
        max_age = int(age_range[1])
        if age >= min_age and age <= max_age:
            age = f"{min_age}-{max_age}"
            break
    return age


def gen_squares_code(number):
    return abs(number)

app/demo/views/__init__.py
from .initial import demo_blueprint  # noqa 401
from .select_features import demo_blueprint  # noqa 401
from .range_groups import demo_blueprint  # noqa 401
from .categories import demo_blueprint  # noqa 401
from .explanations_summary import demo_blueprint  # noqa 401
from .explanations_per_patient import demo_blueprint  # noqa 401
from .financial_select_features import demo_blueprint  # noqa 401
from .financial_range_groups import demo_blueprint  # noqa 401
from .financial_categories import demo_blueprint  # noqa 401
from .financial_explan_summary import demo_blueprint  # noqa 401
from .financial_explan_per_client import demo_blueprint  # noqa 401
from .financial_explan_2_per_client import demo_blueprint  # noqa 401
from .demo import demo_blueprint  # noqa 401

app/demo/views/blueprint.py
from flask import Blueprint

demo_blueprint = Blueprint("demo", __name__)

app/demo/views/categories.py
import json
from flask import session, redirect, url_for, render_template, flash, request
from .blueprint import demo_blueprint
from app.models import Subdomain
from app.demo.forms import CategoriesForm


@demo_blueprint.route("/categories", methods=["GET", "POST"])
def categories():
    form = CategoriesForm(request.form)
    form.selected_features = session.get("selected_features", [])
    form.categories = json.loads(session.get("categories", "{}"))
    form.subdomain = Subdomain.query.get(session.get("subdomain", None))
    # ranges_for_feature = session.get("ranges_for_feature", {})
    if form.validate_on_submit():
        if form.submit.data:
            form.categories[form.category_name.data] = [
                k for k in request.form if request.form[k] == "on"
            ]
            session["categories"] = json.dumps(form.categories)
        if form.next.data:
            if not form.categories:
                flash("Need define at least one category", "danger")
                return render_template("categories.html", form=form)
            session["categories"] = json.dumps(form.categories)
            # {}
            return redirect(url_for("demo.explanations_summary"))
    elif form.is_submitted():
        flash("Invalid data", "warning")

    return render_template("categories.html", form=form)

app/demo/views/demo.py
from flask import render_template, request, session, flash
from flask_login import login_required
from app.models import Subdomain, ModelType
from app.demo.forms import (
    SubdomainChoiceForm,
    InitialForm
)

from .util import redirect_select_features
from .blueprint import demo_blueprint


@demo_blueprint.route("/", methods=["GET", "POST"])
@login_required
def demo():
    form = SubdomainChoiceForm(request.form)
    form_initial = InitialForm(request.form)
    form_initial.generated = session.get("data_generated", False)
    form.subdomains = Subdomain.query.all()
    form.models = ModelType.query.all()
    form.subdomain_id.choices = [(s.id, s.name) for s in form.subdomains]
    form.model_type.choices = [(m.name, m.name) for m in form.models]
    form.active_domain = session.get("active_domain", Subdomain.Domain.initial.name)

    # if we have generated files
    generated_background_file = session.get("generated_background_file", None)
    generated_explainer_file = session.get("generated_explainer_file", None)

    if form.validate_on_submit():
        session["subdomain"] = form.subdomain_id.data
        session["model_type"] = form.model_type.data
        session["active_domain"] = form.domain.data
        bkg_file = request.files.get("bkg_file")
        if not bkg_file:
            if generated_background_file:
                bkg_file = open(generated_background_file, "rb")
            else:
                flash("Need select background file", "warning")
                return render_template("demo.html", form=form, form_initial=form_initial)
        explainer_file = request.files.get("explainer_file")
        if not explainer_file:
            if generated_explainer_file:
                explainer_file = open(generated_explainer_file, "rb")
            else:
                flash("Need select explainer file", "warning")
                return render_template("demo.html", form=form, form_initial=form_initial)

        session["data_generated"] = False
        return redirect_select_features(
            file_value=bkg_file,
            file_explainer=explainer_file,
            domain=form.domain.data,
            subdomain_id=form.subdomain_id.data,
            model_type=form.model_type.data
        )

    elif form.is_submitted():
        session["active_domain"] = form.domain.data
        flash("Invalid data", "warning")

    return render_template("demo.html", form=form, form_initial=form_initial)

app/demo/views/explanations_per_patient.py
import json
from flask import request, session, render_template, flash
from flask_wtf import FlaskForm
from .blueprint import demo_blueprint

from app.models import Feature, Subdomain, CaseValue
from app.demo.controller import (
    age_range_groups,
    gen_squares_code,
    prediction_score,
    predicted,
)


@demo_blueprint.route("/explanations_per_patient/<case_id>", methods=["GET", "POST"])
def explanations_per_patient(case_id):
    form = FlaskForm(request.form)
    form.selected_features = session.get("selected_features", [])
    form.categories = json.loads(session.get("categories", "{}"))
    form.subdomain = Subdomain.query.get(session.get("subdomain", None))
    ranges_for_feature = session.get("ranges_for_feature", {})
    range_groups_ages = ranges_for_feature.get("Age", [])
    all_case_values_query = CaseValue.query.filter(
        CaseValue.user_data_id == session["user_data_id"]
    )
    all_case_values_query_for_patient = all_case_values_query.filter(
        CaseValue.case_id == case_id
    )
    form.presentation_type = "Proportional to the Total Confidence Score"

    if form.validate_on_submit():
        form.presentation_type = request.form["presentation_type"]
    elif form.is_submitted():
        flash("Invalid data", "warning")

    form.table_heads = []
    sum_explainer = {}
    sum_explainer_abs = {}
    for cat_name in form.categories:
        sum_explainer[cat_name] = 0
        sum_explainer_abs[cat_name] = 0
        for feature_name in form.categories[cat_name]:
            feature = Feature.query.filter(Feature.name == feature_name).first()
            case_val = all_case_values_query_for_patient.filter(
                CaseValue.feature_id == feature.id
            ).first()
            sum_explainer[cat_name] += case_val.explainer
            sum_explainer_abs[cat_name] += abs(case_val.explainer)
        form.table_heads += [[cat_name, ], "Feature Contribution"]
    form.table_rows = []
    num_of_rows = max([len(form.categories[k]) for k in form.categories])
    for cat_name in form.categories:
        row_index = 0
        for feature_name in form.categories[cat_name]:
            if len(form.table_rows) <= row_index:
                form.table_rows += [[]]
            feature = Feature.query.filter(Feature.name == feature_name).first()
            case_val = all_case_values_query_for_patient.filter(
                CaseValue.feature_id == feature.id
            ).first()
            if form.presentation_type == "Proportional to the Total Confidence Score":
                one_square_val = sum(sum_explainer_abs.values()) / 12
                square_num = int(round(abs(case_val.explainer) / one_square_val, 0))
                form.table_rows[row_index] += [
                    [feature_name, gen_squares_code(square_num)]
                ]
            else:
                each_category_squares = 12 / len(form.categories)
                value_of_square = int(round(100 / each_category_squares, 0))
                sum_explainer_category = sum_explainer_abs[cat_name]
                feature_explainer = int(
                    (case_val.explainer / sum_explainer_category) * 100
                )
                feature_squares = int(round((feature_explainer / value_of_square), 0))
                form.table_rows[row_index] += [
                    [feature_name, gen_squares_code(feature_squares)]
                ]
            row_index += 1
        for i in range(row_index, num_of_rows):
            if len(form.table_rows) <= i:
                form.table_rows += [[]]
            form.table_rows[i] += [["", ""]]
    explainers = sum((list(map(abs, sum_explainer.values()))))
    values = list(
        map(lambda val: int(round(val * 100 / explainers, 0)), sum_explainer.values())
    )
    form.value_percent = max(values)
    for i, percent in enumerate(values):
        form.table_heads[2 * i] += [percent]

    age_feature = Feature.query.filter(Feature.name == "Age").first()
    age_case_val = all_case_values_query_for_patient.filter(
        CaseValue.feature_id == age_feature.id
    ).first()

    form.age = int(age_case_val.value)
    form.age = age_range_groups(range_groups_ages, form.age)
    form.case_id = case_id
    form.prediction_score = prediction_score(age_case_val.prediction)
    form.predicted = predicted(form.prediction_score)

    def check_is_list(val):
        return type(val) is list

    return render_template(
        "explanations_per_patient.html",
        form=form,
        check_is_list=check_is_list,
        enumerate=enumerate,
    )

app/demo/views/explanations_summary.py
import json
from flask import request, session, render_template, flash
from flask_wtf import FlaskForm
from .blueprint import demo_blueprint

from app.models import Feature, Subdomain, CaseValue
from app.demo.controller import age_range_groups


@demo_blueprint.route("/explanations_summary", methods=["GET", "POST"])
def explanations_summary():
    form = FlaskForm(request.form)
    categories = json.loads(session.get("categories", "{}"))
    form.subdomain = Subdomain.query.get(session.get("subdomain", None))
    ranges_for_feature = session.get("ranges_for_feature", {})
    range_groups_ages = ranges_for_feature.get("Age", [])
    form.presentation_type = "Percents"
    if form.validate_on_submit():
        form.presentation_type = request.form["presentation_type"]
    elif form.is_submitted():
        flash("Invalid data", "warning")

    form.table_heads = [
        "Patient ID",
        "Age",
        f"{form.subdomain.name} Predicted",
        "Prediction_or_Confidence Score (Out of 100)",
    ]

    form.table_heads += [f"{name} Contribution" for name in categories]

    all_case_values_query = CaseValue.query.filter(
        CaseValue.user_data_id == session["user_data_id"]
    )
    max_patient_id = max([v.case_id for v in all_case_values_query.all()])
    form.table_rows = []
    for patient_id in range(max_patient_id + 1):
        all_case_values_query_for_patient = all_case_values_query.filter(
            CaseValue.case_id == patient_id
        )
        if not all_case_values_query_for_patient.all():
            continue
        age_feature = Feature.query.filter(Feature.name == "Age").first()
        age_case_val = all_case_values_query_for_patient.filter(
            CaseValue.feature_id == age_feature.id
        ).first()
        age = int(age_case_val.value)
        age = age_range_groups(range_groups_ages, age)
        prediction_score = int(round(age_case_val.prediction, 2) * 100)
        predicted = "No" if prediction_score < 50 else "Yes"
        prediction_score_color = "green"
        if prediction_score > 45:
            prediction_score_color = "yellow"
            if prediction_score > 70:
                prediction_score_color = "red"

        row = [
            (patient_id, None),
            (age, None),
            (predicted, None),
            (prediction_score, prediction_score_color),
        ]
        explainers = []
        explainers_abs_values = []
        for cat_name in categories:
            sum_explainer = 0
            for feature_name in categories[cat_name]:
                feature = Feature.query.filter(Feature.name == feature_name).first()
                case_val = all_case_values_query_for_patient.filter(
                    CaseValue.feature_id == feature.id
                ).first()
                sum_explainer += case_val.explainer
            explainers += [sum_explainer]
            explainers_abs_values += [abs(sum_explainer)]
        # if not selected percentage
        cells = None

        if form.presentation_type == "Percents":
            hundred = sum(explainers_abs_values)
            values = list(
                map(lambda val: int(round(val * 100 / hundred, 0)), explainers)
            )
            max_val = max(values)
            colors = list(map(lambda val: ("red" if val == max_val else None), values))
            values = map(lambda val: f"{val}%", values)
            cells = list(zip(values, colors))
        else:
            values = list(map(lambda val: (round(val, 3)), explainers))
            max_val = max(values)
            colors = list(map(lambda val: ("red" if val == max_val else None), values))
            cells = list(zip(values, colors))
        row += cells
        form.table_rows += [row]

    return render_template(
        "explanations_summary.html",
        form=form,
        range_groups_ages=range_groups_ages,
        len=len,
    )

app/demo/views/financial_categories.py
import json
from flask import session, redirect, url_for, render_template, flash, request
from .blueprint import demo_blueprint
from app.models import Subdomain
from app.demo.forms import CategoriesForm


@demo_blueprint.route("/financial_categories", methods=["GET", "POST"])
def financial_categories():
    form = CategoriesForm(request.form)
    form.selected_features = session.get("selected_features", [])
    form.categories = json.loads(session.get("categories", "{}"))
    form.subdomain = Subdomain.query.get(session.get("subdomain", None))
    # ranges_for_feature = session.get("ranges_for_feature", {})
    if form.validate_on_submit():
        if form.submit.data:
            form.categories[form.category_name.data] = [
                k for k in request.form if request.form[k] == "on"
            ]
            session["categories"] = json.dumps(form.categories)
        if form.next.data:
            if not form.categories:
                flash("Need define at least one category", "danger")
                return render_template("categories.html", form=form)
            session["categories"] = json.dumps(form.categories)
            # {}
            return redirect(url_for("demo.financial_explan_summary"))
    elif form.is_submitted():
        flash("Invalid data", "warning")
    return render_template("financial_categories.html", form=form)

app/templates/categories.html
{% extends "base.html" %}
{% block content %}
<!-- Header -->

<style>
.ex-header-top-main {
  padding: 15px;
  text-align: left;
  font-family: 'serif';
  width: 100%;
  color: #FFF5EE;
  font-style: normal;
  font-size: 250%;
  padding-top: 2.6rem;
  padding-bottom: 1rem;

  background: -webkit-linear-gradient(top, #a5e7e7, #00BFFF);
}

.th_ > h5 {
  font-weight: 600;
}

</style>

<!-- <div id="header" class="ex-header"></div> -->
<!-- <div class="container" style="margin-bottom: 5%; margin-left: 0%;"> -->
<div class="ex-header-top-main" title='Healthcare – {{ form.subdomain.name }} Diagnosis'>
  Healthcare – {{ form.subdomain.name }} Diagnosis
</div>
<h4>
  <b>Categorize Features</b>
</h4>
  <!-- Flash Messages BEGIN -->
<div>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }} alert-dismisible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
</div>
<!-- Flash Messages END -->
<form class="form" role="form" action="{{ url_for('demo.categories') }}" method="post">
  {{ form.csrf_token }}
<table cellspacing="1" style="
    margin-bottom: 20%;
    background: #FFFAFA;
    width: 100%;
    border-collapse: collapse;" height="520">
  <tbody>
    <tr>
    <td>
      <br>
      <h4 style="padding: 8px;">Create a category:</h4>
    </td>
    <td><br></td>
    </tr>
    <tr>
      <td>
        <div>
        <table>
          <tr>
            <td  style="padding: 8px;"><h5>{{ form.category_name.label }}</h5></td>
            <td>{{ form.category_name(class="form-control") }}</td>
          </tr>
        </table>
        </div>
      </td>
    </tr>
    <tr>
      <div>
      <td>
        <div>
          <table>
            <thead>
              <th class="th_" style="padding: 10px;"><h5>Select</h5></th>
              <th class="th_" style="padding: 10px;"><h5>Feature</h5></th>
            </thead>
            <tbody>
              {% for feature in form.selected_features %}
              <tr>
                <td style="text-align:left;"><input class="form-control" type="checkbox" name="{{feature}}"></td>
                <td style="text-align:left;"><h5>{{feature}}</h5></td>
              </tr>
              {% endfor %}
              <tr>
                <td></td>
                <td><div style="margin-top: 10px; margin-bottom: 10px; padding: 8px;">{{ form.submit(class="btn-solid-lg page-scroll", style="width: 250px; font-size: 150%;") }}</div></td>
              </tr>
            </tbody>
          </table>
        </div>
      </td>
      </div>
      <td style="border: 3px outset lightskyblue;" valign="top">
        <div>
          {% for category in form.categories %}
          <h5>{{category}}</h5>
          <ul>
            {% for feature in form.categories[category] %}
            <li>{{feature}}</li>
            {% endfor %}
          </ul>
          {% endfor %}
        </div>
      </td>
    </tr>
    <tr>
      <td><div style="margin-top: 10px; margin-bottom: 10px; padding: 8px;"><a class="btn-solid-lg page-scroll" href="{{ url_for('demo.range_groups') }}" style='font-size: 150%;'>Go Back</a></div></td>
      <td><div style="margin-top: 10px; margin-bottom: 10px; text-align:right; padding: 8px;">{{ form.next(class="btn-solid-lg page-scroll", style="width: 250px; font-size: 150%;") }}</div></td>
    </tr>
  </tbody>
</table>
</form>
<!-- </div> -->
{% endblock %}

app/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron my-4">
  <div class="text-center">
    <h1>{{ '%s - %s' % (error.code, error.name) }}</h1>
    <p>{{ error.description }}.</p>
  </div>
</div>
{% endblock %}

app/templates/explanations_summary.html
{% extends "base.html" %}

{% block links %}
<link rel="stylesheet" href="/static/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="/static/css/explanations_per_patient.css">
{% endblock %}

{% block content %}
<!-- Header -->
<!-- fix problem with loading from static css -->
<style>
  .healthHeader {
    padding: 10px 5px;
    background-color: blue;
    color: white;
}

.table {
    border: 3px ridge lightskyblue;
    background: #FFFAFA;;
    width: 100%;
    height: 100%;
}

.sidesWrapper {
    display: flex;
    justify-content: space-between;
}

.routeButton {
    padding: 5px 20px;
    background-color: aqua;
    color: white;
    cursor: pointer;
}

.prediction {
    margin-right: 50px;
}

.explanations {
  background: #FFD55F;
  border: 2px solid rgb(241, 217, 76);
  text-align: center;
  font-size: 140%;
  color: #FFFAFA;
  font-family: 'arial';
}

.patientsTable {
    margin-top: 18px;
    max-width: 120vw;
    width: 120vh;
}

.patientsTable>thead {
    background-color: rgb(243, 243, 232);
    border: 3px solid rgb(243, 243, 125);
}

/* .bckcoloroption {
    background: -webkit-linear-gradient(top, #00BFFF, #FFF5EE);
} */

.ex-header-top-main {
    padding: 15px;
    text-align: left;
    font-family: 'serif';
    width: 100%;
    color: #FFF5EE;
    font-style: normal;
    font-size: 250%;
    padding-top: 2.6rem;
    padding-bottom: 1rem;

    background: -webkit-linear-gradient(top, #a5e7e7, #00BFFF);
}

.centerDiv {
    display: block;
    width: 35vh;
    margin-top: 38px;
    margin-left: 35px;
}


.table .leftDiv .centerDiv {
    display: flex;
    flex-direction: row;
    justify-content: space-around;

}


.rightDiv {
    width: 170vh;
    text-align: left;
    padding: 10px;
    margin-top: 10px;
    margin-left: 55px;
}

.frame{
    float:left;
    width: 50%;
}

.div-style-font{
font-family: 'arial';
font-weight: 600;
}

.dropdown {
  border: 1px solid rgb(16, 25, 29);
  background: -webkit-linear-gradient(top, #a5e7e7, #00BFFF);
  width: 68%;
}


</style>
<!-- <div class="container" style="margin-bottom: 0%; margin-left: 0%;"></div> -->
<div class="ex-header-top-main bck" title='Healthcare – {{ form.subdomain.name }} Diagnosis'>
  Healthcare – {{ form.subdomain.name }} Diagnosis
</div>
  <!-- Flash Messages BEGIN -->
<div>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }} alert-dismisible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
</div>
  <!-- Flash Messages END -->
<form class="form" role="form" action="{{ url_for('demo.explanations_summary') }}" method="post">
  {{ form.csrf_token }}
  <main class="table">
    <div style="width: 100%;">
      <section >
        <div class="sidesWrapper">
          <div class="rightDiv">
            <div style="margin-left: 80px;">
              <header>
                <h5><b>View Explanations (Summary)</b></h5>
              </header>
              <div>
                <h5>Prediction Score & Category Contributions:</h5>
              </div>
              <h5>How to view Contributions: </h5>
              <div>
                <select class="form-control" style="width: 400px;" id="presentation_type" name="presentation_type" onchange="this.form.submit()">
                  {% if form.presentation_type == "Percents" %}
                  <option class="bckcoloroption" selected value="Percents">Percentage of Contributions Per Row</option>
                  <option class="bckcoloroption" value="Values">Contribution Value</option>
                  {% else %}
                  <option class="bckcoloroption" value="Percents">Percentage of Contributions Per Row</option>
                  <option class="bckcoloroption" selected value="Values">Contribution Value</option>
                  {% endif %}
                </select>
              </div>
            </div>
            <div style="margin-bottom: 40px;"></div>
            <table id="patientsTable" class="patientsTable table table-striped table-sm">
              <thead class="own_table">
                <tr>
                  <td colspan="4"></td>
                  <div>
                  <td class="explanations" colspan="{{ len(form.table_heads) - 4 }}">Explanations</td>
                  </div>
                </tr>
                <tr>
                {% for head in form.table_heads %}
                  <th style="text-align: center;">{{head}}</th>
                {% endfor %}
                </tr>
              </thead>
              <tbody style="text-align: center;">
                {% for row in form.table_rows %}
                <tr>
                  <td><a style="color: #c04702;" href="{{url_for('demo.explanations_per_patient', case_id=row[0][0])}}">{{row[0][0]}}</a></td>
                  {% for cell in row[1:] %}
                  {% if cell[1] %}
                  <td style="background-color: {{cell[1]}};">{{cell[0]}}</td>
                  {% else %}
                  <td >{{cell[0]}}</td>
                  {% endif %}
                  {% endfor %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div style="display: flex; justify-content: space-between;"></div>
          <div style="margin-top: 10px; margin-bottom: 35px; margin-left: 15px; padding: 12px;"><a
              class="btn-solid-lg page-scroll" href="{{ url_for('demo.categories') }}" style='font-size: 150%;'>Go
              Back</a>
          </div>
        </div>
      </section>
    </div>
  </main>
</form>

{% endblock %}

{% block scripts %}
<script src="/static/js/jquery.dataTables.min.js"></script>
{% endblock %}

app/templates/financial_categories.html
{% extends "base.html" %}
{% block content %}
<!-- Header -->

<style>
  .ex-header-top-main {
    padding: 15px;
    text-align: left;
    font-family: 'serif';
    width: 100%;
    color: #FFF5EE;
    font-style: normal;
    font-size: 250%;
    padding-top: 2.6rem;
    padding-bottom: 1rem;

    background: -webkit-linear-gradient(top, #a5e7e7, #00BFFF);
  }
</style>
<div class="ex-header-top-main" title='Financial – Assessing {{ form.subdomain.name }}'>
  Financial – Assessing {{ form.subdomain.name }}
</div>
<h4>
  <b>Categorize Features</b>
</h4>
<form class="form" role="form" action="{{ url_for('demo.financial_categories') }}" method="post">
  {{ form.csrf_token }}
  <table cellspacing="1" style="
    margin-bottom: 20%;
    background: #FFFAFA;
    width: 100%;
    border-collapse: collapse;" height="520">
    <tbody>
      <tr>
        <td>
          <div>
            <h4 style="padding: 8px;">Create a category:</h4><br>
        </td>
        <td><br></td>
      </tr>
      <tr>
        <td>
          <div>
            <table>
              <tr>
                <td style="padding: 8px;">
                  <h5>{{ form.category_name.label }}</h5>
                </td>
                <td>{{ form.category_name(class="form-control") }}</td>
              </tr>
            </table>
          </div>
        </td>
      </tr>
      <tr>
        <div>
          <td>
            <div>
              <table>
                <thead>
                  <th style="padding: 8px;">Select</th>
                  <th style="padding: 8px;">Feature</th>
                </thead>
                <tbody>
                  {% for feature in form.selected_features %}
                  <tr>
                    <td style="text-align:left;"><input class="form-control" type="checkbox" name="{{feature}}"></td>
                    <td style="text-align:left;">
                      <h5>{{feature}}</h5>
                    </td>
                  </tr>
                  {% endfor %}
                  <tr>
                    <td></td>
                    <td>
                      <div style="margin-top: 10px; margin-bottom: 10px; padding: 8px;">
                        {{ form.submit(class="btn-solid-lg page-scroll", style="width: 250px; font-size: 150%;") }}
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </td>
          <td style="border: 3px outset lightskyblue;" valign="top">
            <div>
              {% for category in form.categories %}
              <h5>{{category}}</h5>
              <ul>
                {% for feature in form.categories[category] %}
                <li>{{feature}}</li>
                {% endfor %}
              </ul>
              {% endfor %}
            </div>
          </td>
      </tr>
      <tr>
        <td>
          <div style="margin-top: 10px; margin-bottom: 10px; padding: 8px;"><a class="btn-solid-lg page-scroll"
              href="{{ url_for('demo.financial_range_groups') }}" style='font-size: 150%;'>Go Back</a></div>
        </td>
        <td>
          <div style="margin-top: 10px; margin-bottom: 10px; text-align:right; padding: 8px;">
            {{ form.next(class="btn-solid-lg page-scroll", style="width: 250px; font-size: 150%;") }}</div>
        </td>
      </tr>
    </tbody>
  </table>
</form>

{% endblock %}